### PR TITLE
Speed up namespace switching in big clusters

### PR DESCRIPTION
**Pull request by imbstack**
Hi, thank you so much for this tool, it is the best one of its kind!

This patch just switches the check that a namespace exists from listing all namespaces to seeing if a specific label exists. This doesn't make much difference on clusters with reasonable numbers of namespaces but for me it is roughly a 8 second speedup:

```sh
$ time (kubechn namespace)      
Context "context" modified.
Switched to namespace "namespace"
( kubechn namespace; )  5.32s user 0.23s system 61% cpu 8.978 total

# switch to this patch

$ time (kubechn namespace)       
Context "context" modified.
Switched to namespace "namespace"
( kubechn namespace; )  0.21s user 0.06s system 39% cpu 0.714 total
```

This label should [always exist in 1.22+ clusters](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#automatic-labelling). I expect relying on this would break `kubechc` for clusters older than that? Happy to make this fallback to the listing-all-namespaces way when the label check fails or something along those lines. Whatever sounds best to you.

Thanks again!

### CODE REVIEW

**Comment by aabouzaid** [comment]
@imbstack, thanks for your PR, that's a pretty good addition :rocket: 
since this feature is a bit new, I'd suggest making it disabled by default and enabling it by a flag (env var).

Later on, we can flip the flag and make it the default and keep the old style for anyone who works with older K8s versions.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will merge the PR once it has a flag (env var) to control the feature as mentioned.

**Comment by imbstack** [comment]
Ah yes sorry, I've been busy lately. I'll get a patch with that change before too long!

**Comment by imbstack** [comment]
Finally got around to this. I've tested this with the env var unset, and set to both listed values across the following cases:

1. namespace passed in and exists
2. namespace passed in and does not exist
3. no namespace passed in

I believe it works correctly in all of those cases. That said, I'm not a shell scripting expert so if there's a better way to go about any of this I'm happy to change whatever!

**Comment by imbstack** [comment]
I'll update README usage and such if this looks good!

**Comment by aabouzaid** [comment]
@imbstack Thanks for the change.
Apart from the typo, as shown in the CI pipeline, the current implementation is a bit complex.

You can simplify it by setting the default value the same way as here:
https://github.com/aabouzaid/kubech/blob/9f11a5486152de8ea13ef0fc1e269187ecaa7db5/kubech#L10

if you don't want to bother, I can do the whole change anyway.

**Comment by imbstack** [comment]
Ah, good call! Hopefully this is more what you're thinking of. If not, feel free to edit or drop the PR and make it yourself. Thanks again!

**Review by aabouzaid — APPROVED** [review]

**Comment by aabouzaid** [comment]
@imbstack I've made a small fix and it's ready to merge.
Thanks for your contribution Brian :bow:

**Pull request merged**
